import { useCallback } from 'react';
import { useStoredState } from './useStoredState';

const STORAGE_KEY = 'cardinal.ignorePaths';
const DEFAULT_IGNORE_PATHS = [
  '# System volumes and large bundled trees.',
  '/Volumes/',
  '/Applications/',
  '/cores/',
  '/dev/',
  '/private/',
  '/System/iOSSupport/System/Library/',
  '/System/Library/',
  '/System/Volumes/',
  '/usr/share/',
  '/xarts/',
  '/Library/Apple/System/Library/PrivateFrameworks/',
  '/Library/Application Support/Apple/BezelServices/',
  '/System/Applications/**/Contents/Resources/',
  '',
  '# Developer tools and generated build outputs.',
  '/Library/Developer/CoreSimulator/Volumes/',
  '/Library/Developer/CommandLineTools/',
  '/opt/homebrew/Cellar/',
  '/opt/homebrew/share/',
  '~/Library/Developer/CoreSimulator/Devices/',
  '~/.rustup/toolchains/',
  '~/.cursor/extensions/',
  '~/.nuget/packages/',
  '**/Library/Developer/Xcode/DerivedData/',
  '**/target/',
  '**/.next/',
  '**/Xcode.app/',
  '',
  '# Dependencies and package manager stores.',
  '**/node_modules/',
  '**/.pnpm/',
  '~/Library/pnpm/store',
  '**/Library/pnpm/store/',
  '**/.bun/install/cache/',
  '**/.npm/_cacache/',
  '**/.gradle/caches/',
  '**/.cargo/registry/',
  '',
  '# Caches and runtime storage.',
  '**/Library/Caches/',
  '**/Library/Application Support/*/Partitions/*/Cache/',
  '**/Library/Application Support/*/Cache/',
  '**/Code Cache/',
  '**/Service Worker/CacheStorage/',
  '**/IndexedDB/',
  '**/WebStorage/',
  '**/Library/WebKit/**/WebsiteDataStore/',
  '~/Library/Application Support/Cursor/User/History/',
  '~/Library/Application Support/Code*/User/History/',
  '~/.claude/plugins/cache/',
  '**/Library/Logs/DiagnosticReports/',
  '**/Library/Application Support/CrashReporter/',
  '**/Library/Application Support/Code/User/globalStorage/',
  '**/Library/Application Support/Google/Chrome*/',
  '**/Library/Application Support/Google/GoogleUpdater/',
  '**/Library/Preferences/',
  '**/Chromium/**/GPUCache/',
  '**/BraveSoftware/Brave-Browser*/**/GPUCache/',
  '**/Microsoft Edge*/**/GPUCache/',
  '**/Arc/**/GPUCache/',
  '**/Vivaldi*/**/GPUCache/',
  '**/Chromium/**/Local Storage/leveldb/',
  '**/BraveSoftware/Brave-Browser*/**/Local Storage/leveldb/',
  '**/Microsoft Edge*/**/Local Storage/leveldb/',
  '**/Arc/**/Local Storage/leveldb/',
  '**/Vivaldi*/**/Local Storage/leveldb/',
  '**/Firefox/Profiles/**/sessionstore-backups/',
  '**/Firefox/Profiles/**/storage/default/',
  '**/Firefox/Profiles/**/storage/permanent/',
  '**/Spotify/Users/',
  '**/*.com.google.Chrome',
  '**/webappsstore.sqlite-wal',
  '',
  '# App-specific local data.',
  '~/Library/CloudStorage',
  '~/Library/Containers/',
  '~/Library/Group Containers/',
  '~/.codex-profiles/*/tmp/',
  '**/.local/share/',
  '**/.local/fsindex*',
  '**/com.docker.docker/Data/',
  '**/IconJar*/Backups/',
  '**/Sublime Text */Index/',
  '**/io.tailscale.ipn.macos/',
  '**/wharf/',
  '~/Library/Biome',
  '~/Library/DuetExpertCenter',
  '',
  '# Common metadata and disposable directories.',
  '**/.cache/',
  '**/.git/',
  '**/.gitignore',
  '**/.lock',
  '**/.bower.json',
  '**/.github',
  '**/__pycache__/',
  '**/.cocoapods/',
  '**/.opam/',
  '**/Cache/',
  '**/Caches/',
  '**/Index.noindex/',
  '**/TextIndex/',
  '**/.stversions/',
  '**/*.db-shm',
  '**/*.pyc',
  '**/.dat.nosync*',
  '**/.DS_Store',
  '**/bower_components/',
  '',
  '# Database internals.',
  '**/var/postgres/base/',
  '**/var/postgres/pg_stat_tmp/',
  '**/var/postgres/pg_wal/',
];

const keepStringEntries = (next: unknown[]): string[] =>
  next.filter((item): item is string => typeof item === 'string');

export function useIgnorePaths() {
  const [ignorePaths, setIgnorePathsState] = useStoredState<string[]>({
    key: STORAGE_KEY,
    defaultValue: DEFAULT_IGNORE_PATHS,
    read: (raw) => {
      const parsed = JSON.parse(raw);
      if (!Array.isArray(parsed)) return null;
      return keepStringEntries(parsed);
    },
    write: (value) => JSON.stringify(value),
    readErrorMessage: 'Unable to read saved ignore paths',
    writeErrorMessage: 'Unable to persist default ignore paths',
  });

  const setIgnorePaths = useCallback(
    (next: string[]) => {
      setIgnorePathsState(next);
    },
    [setIgnorePathsState],
  );

  return { ignorePaths, setIgnorePaths, defaultIgnorePaths: DEFAULT_IGNORE_PATHS };
}
